Geometry: M_PI (`<cmath>`)
Missing include leads to compile error on Windows:
```
build\temp.win-amd64-cpython-37\Release\1\_deps\fetchedamrex-src\Src\Base\AMReX_Geometry.H(255,39):
error C2065: 'M_PI': undeclared identifier
[C:\Users\VssAdministrator\AppData\Local\Temp\pip-req-build-9ov6s5p1\build\temp.win-amd64-cpython-37\Release\1\_deps\fetchedamrex-build\Src\amrex.vcxproj]
```

Technically, we also need to define `_USE_MATH_DEFINES` (we do that
in WarpX).