CI: oneAPI -Wmissing-braces (#3239)
## Summary

The latest oneAPI release, 2023.1.10, ships with `-Wmissing-braces`
warnings in the public MKL headers...

```
/opt/intel/oneapi/mkl/2023.1.0/include/oneapi/mkl/rng/device/detail/mrg32k3a_impl.hpp:163:33: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    std::uint32_t temp[3][3] = {1, 0, 0, 0, 1, 0, 0, 0, 1};
                                ^~~~~~~
                                {      }
/opt/intel/oneapi/mkl/2023.1.0/include/oneapi/mkl/rng/device/detail/mrg32k3a_impl.hpp:163:42: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    std::uint32_t temp[3][3] = {1, 0, 0, 0, 1, 0, 0, 0, 1};
                                         ^~~~~~~
                                         {      }
/opt/intel/oneapi/mkl/2023.1.0/include/oneapi/mkl/rng/device/detail/mrg32k3a_impl.hpp:163:51: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    std::uint32_t temp[3][3] = {1, 0, 0, 0, 1, 0, 0, 0, 1};
                                                  ^~~~~~~
                                                  {      }
```

## Additional background

Broke our CI.

attn @rscohn2 FYI - let's report this? :)

## Checklist

The proposed changes:
- [ ] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX
users
- [ ] include documentation in the code and/or rst files, if appropriate