Use ROCm 4.3 in CI (#2280)
* Use ROCm 4.3 in CI

Since the VOP bug has been fixed in the latest ROCm release v4.3, CI can use
the latest ROCm release now instead of 4.1.

* Work-Around: OpenMPI 4.0.3 on Ubuntu 20.04

"mpic++ --showme" forgets to link open-pal
```
/opt/rocm/llvm/bin/clang++       -pthread CMakeFiles/cmTC_abf94.dir/test_mpi.cpp.o  -o cmTC_abf94  -Wl,-rpath,/usr/lib/x86_64-linux-gnu/openmpi/lib /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
ld.lld: error: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to opal_class_init_epoch [--no-allow-shlib-undefined]
ld.lld: error: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to opal_list_item_t_class [--no-allow-shlib-undefined]
ld.lld: error: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to opal_class_initialize [--no-allow-shlib-undefined]
ld.lld: error: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to opal_uses_threads [--no-allow-shlib-undefined]
```

Results in `MPI_CXX` being not found.

Co-authored-by: Axel Huebl <axel.huebl@plasma.ninja>