Fix uninitialized compiler warnings for: xslope yslope zslope (#1371)
## Summary

Getting compiler warnings when building MFiX-Exa file that includes `AMReX_EB_slopes_K.H`

## Additional background

Building with GCC 7.5.0:
```
../src/convection/mfix_slopes.cpp: In member function 'void mfix::mfix_compute_slopes(int, amrex::Real, amrex::MultiFab&, const amrex::Vector<amrex::MultiFab*>&, const amrex::Vector<amrex::MultiFab*>&, const amrex::Vector<amrex::MultiFab*>&, int, std::map<std::__cxx11::basic_string<char>, amrex::PODVector<int, std::allocator<int> > >&)':
../src/convection/mfix_slopes.cpp:235:52: error: 'zslope' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                        zs_fab(i,j,k,slopes_comp+n) = eb_slopes[2];
../src/convection/mfix_slopes.cpp:216:52: error: 'yslope' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                        ys_fab(i,j,k,slopes_comp+n) = eb_slopes[1];
../src/convection/mfix_slopes.cpp:197:52: error: 'xslope' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                        xs_fab(i,j,k,slopes_comp+n) = eb_slopes[0];
```

## Checklist

The proposed changes:
- [X] fix a bug or incorrect behavior in AMReX
- [ ] add new capabilities to AMReX
- [ ] changes answers in the test suite to more than roundoff level
- [ ] are likely to significantly affect the results of downstream AMReX users
- [ ] are described in the proposed changes to the AMReX documentation, if appropriate


Co-authored-by: Mark Meredith <mark.meredith@netl.doe.gov>