CMake 3.20+ CUDA: Policy & Include (#2074)
## Summary

Do not include the deprecated CUDA setup with CMake 3.20+ and support new policy for CUDA_ARCHITECTURES.

Also fix errors of the kind:
```
ERROR: set_target_properties called with incorrect number of arguments.
Value in AMREX_CUDA_ARCHS is 53;60;61;70;75;80;86;86
```
by quoting the semicolon-separated list.

## Additional background

Those are regressions to #2012 that appear with our modernized logic in CMake 3.20+ with CUDA.

I saw those regressions with [HiPACE++](https://github.com/Hi-PACE/hipace).