Avoid clang warnings with -Wshadow-field (#5197)
Compiling with clang++ and -Wshadow-field I get warnings:
```
AMReX_MLEBTensorOp.H:96:10: error: non-static data member 'm_needs_update' of 'MLEBTensorOp' shadows member inherited from type 'MLEBABecLap' [-Werror,-Wshadow-field]
```
Each class in the LinearSolvers/MLMG/ hierarchy has its own
`m_needs_update`. Some of these are `protected` and some are `private`.
Inheriting from the `protected` ones causes the shadowing warning. This
patch makes them all `private` which resolves the warnings. (I don't
believe there's a reason for them to be `protected` rather than
`private` as they are accessed in subclasses through the `needsUpdate`
function rather than direct member access.)

Co-authored-by: Charles G Waldman <cgw@alum.mit.edu>